#!/bin/bash

# Check argument
if [ $# -lt 1 ]; then
  echo 1>&2 "$0: not enough arguments!"
  exit 2
fi

# Check 
if [ -d "$1" ]; then
  echo "$0: '$1' already exists!"
  exit 2
fi

# Initialize the project
mkdir $1
cd $1

# Generate the template
rm src/*
cd src
mkdir lib
cd lib
curl -o Scroll.js https://raw.githubusercontent.com/nickxsy/components/refs/heads/main/Scroll/Scroll.js
cd ../..

# Modify package.json
# rm package.json
# curl -o package.json https://gist.githubusercontent.com/aakashns/6a405588a1b25e15a78e92d797919895/raw/60c59b3d18f636b850071a252b2e6589f8d752df/package.json
# sed -i '' "2s/simple-component-library/$1/" package.json
# npm i react react-dom react-scripts babel-cli babel-preset-react-app rimraf --save-dev

# Set up transpilation
# echo '{ "presets": [["react-app", { "absoluteRuntime": false }]] }' > .babelrc 

# Set up linting
# echo '{ "extends": "react-app" }' > .eslintrc

# Rewite the README
# echo "# $1" > README.md
